### ISSUE TITLE
Unittest ListBoxTestCases.testItemCount fails on different locale settings

### ISSUE THREAD

**Issue by airelil** [vasily-v-ryabov/pywinauto-64#11]
The test is failing on my machine because the "Date and Time" dialog has 10 items instead of expected eight. Looks as it depends on locale settings. I got the expected number 8 when I had switched the locale to 'ru_RU'/'cp1251'. I'd propose the fix with checking the machine locale settings:

```python
import locale
...

default_locale = locale.getdefaultlocale()
expected_num_items = 0
if default_locale[0] == 'ru_RU':
    expected_num_items = 8
elif default_locale[0] == 'en_GB':
    expected_num_items = 10
else:
    print(default_locale)

self.assertEquals(self.ctrl.ItemCount(), expected_num_items)
```
If you like the proposed solution I could create a pull request for it

Another possible solution would be running tests on a reference system. Take a look on CI builds I setup at apvoyer.com:
https://ci.appveyor.com/project/airelil/pywinauto-64
It has matrix of four configurations: py27/py34 vs win32/win64

**Comment by vasily-v-ryabov** [comment]
It looks like test app bug. I built List View.exe by simply adding x64 build configuration. Initial source code may not be targeted for x64 architecture. Item count should always be 9. I could not find appropriate x64-compatible source code for ControlSpy set.

**Comment by airelil** [comment]
Hi @vasily-v-ryabov. I think we are talking about different tests. I meant *ListBoxTestCases.testItemCount* in *test_win32controls.py*. The test creates a wordpad application and opens a "Date and Time" dialog.  BTW, on Windows VMs on [Appveyor](https://ci.appveyor.com/project/airelil/pywinauto-64/build/job/4wqy14ef76oy6pmp) the test fails with 13 actual items vs 8 expected:
```
Traceback (most recent call last):
  File "C:\projects\pywinauto-64\pywinauto\unittests\test_win32controls.py", line 296, in testItemCount
    self.assertEquals(self.ctrl.ItemCount(), 8)
AssertionError: 13 != 8
```
Notice that you changed it once to suit for the output on your machine in 21eb32facd8986923f4b5416b14ba4fe1acb95bc

**Comment by vasily-v-ryabov** [comment]
Oops, sorry, you're right! Such a conditional fix makes sense. Though unified approach should use some locale settings to determine expected item count.

**Comment by vasily-v-ryabov** [comment]
I could not find standard way to enumerate all formats, so asked a question on StackOverflow: http://stackoverflow.com/questions/29407959/how-to-enumerate-available-date-time-formats-like-wordpad-exe-shows

**Comment by vasily-v-ryabov** [comment]
I made workaround and put new test app for that case. Fixed. :)
