### ISSUE TITLE
Unittest DialogTestCases.testClientAreaRect fails

### ISSUE THREAD

**Issue by airelil** [vasily-v-ryabov/pywinauto-64#14]
A unittest from *test_win32controls.py: DialogTestCases.testClientAreaRect* is failing on all machines that I tried to run. I wander, isn't that just a simple fix of 5-pixel offsets in the test itself ?
```python
   def testClientAreaRect(self):
        """Validate that the client area rect is the right size
        (comparing against the full rectangle)"""
        clientarea = self.calc.ClientAreaRect()
        self.assertEquals(self.calc.Rectangle().left + 3+5, clientarea.left)
        self.assertEquals(self.calc.Rectangle().top + 43+7, clientarea.top) #BTW, here the same 5 pix if you diff to original sources
        self.assertEquals(self.calc.Rectangle().right - 3-5, clientarea.right)
        self.assertEquals(self.calc.Rectangle().bottom - 3-5, clientarea.bottom)
```

**Comment by airelil** [comment]
@vasily-v-ryabov, maybe you noticed I tried to adjust the offsets as specified in my previous comment but it didn't work on Windows running on VM at Appveyor:
```
Rectangle: left=182, right=605, top=182, bottom=505
offsets: left=8, right=-8, top=51, bottom=-8
BugType: Overlapping 1
b'OverlappedRect' b'<pywinauto.tests.overlapping.OptRect object at 0x03ACA7F0>'
...
...
FAIL: testClientAreaRect (test_win32controls.DialogTestCases)
Validate that the client area rect is the right size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pywinauto-64\pywinauto\unittests\test_win32controls.py", line 565, in testClientAreaRect
    self.assertEquals(self.calc.Rectangle().top + 50, clientarea.top)
AssertionError: 232 != 233
 
-------------------------------
 ```

**Comment by vasily-v-ryabov** [comment]
Probably some sizes depend on screen resolution. Can you customize AppVeyor VM to make resolution standard? I run tests on Win7 x64 with (1920x1080) and classic theme.

**Comment by airelil** [comment]
I think the difference is in Windows OS version. The Appveyor VMs are running Windows Server 2012 or 2008. with screen size 1024x768. I tried to setup 1920x1080 resolution from a PowerShell script, in order to check if it's related to the screen size or theme, but with no success. Apparently these dimensions are not supported by the VM.
The latest build logs from Appveyor can be found here:
https://ci.appveyor.com/project/airelil/pywinauto-64

**Comment by vasily-v-ryabov** [comment]
OK, I've created WinServer2008 x64 local virtual machine. Many failures are reproduced.

**Comment by airelil** [comment]
I also ran it on local VM WinServer2008. What I saw, there were many crashes of test apps from *pywinauto-64\controlspy0998* dir.  @vasily-v-ryabov  can you provide sources for these apps?

**Comment by vasily-v-ryabov** [comment]
Yes, 64-bit test apps looks built incorrectly. [There are sources I could find](https://drive.google.com/file/d/0B2QBahqR-AGZLVFaSzFSSVJvd0k/view?usp=sharing). I manually added "x64" platform configuration for each solution. But it seems insufficient. I could not find any common controls builds specially ported for x64 with care.

**Comment by vasily-v-ryabov** [comment]
Let's move the discussion to issue #21.
