### ISSUE TITLE
Python 3.4 interpreter crashes in _get_multiple_text_items

### ISSUE THREAD

**Issue by airelil** [vasily-v-ryabov/pywinauto-64#3]
I get the crash in my Python 3.4 interpreter while trying to run unittests. The interpreter crashes in the *_get_multiple_text_items* function from *win32_controls.py*. However it stopped crashing when I replaced ctypes allocation to a unicode version:

    text = ctypes.create_unicode_buffer(text_len + 1)
    #text = ctypes.create_string_buffer(text_len + 1)

So if you want to keep using the *ctypes.create_string_buffer* for the compatibility with python2 you have to calculate the right size for the buffer. If *text_len* variable has value 9 it means that you need to allocate 18 bytes. There is a quick and dirty fix that comes to my mind:

    text = ctypes.create_string_buffer((text_len + 1) * 2)

**Comment by vasily-v-ryabov** [comment]
I fixed crashes, but there are still some encoding issues in returned strings (not everywhere). If you find such cases, please submit additional issues.
